name: Getting Started Test

on:
  push:
    paths:
      - "**.py"
      - "**.yml"
      - "**.yaml"
  workflow_dispatch:

jobs:
  getting_started:
    strategy:
      fail-fast: false
      matrix:
        include:
          - env-prefix: PY37_GCP_BC
            python-version: 3.7
            account-ident: dd99123.europe-west4.gcp

          - env-prefix: PY39_GCP_BC
            python-version: 3.9
            account-ident: dd99123.europe-west4.gcp

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install
        run: pip install -e .

      - name: "Cleanup"
        run: snowddl -c sample01_01 -a ${{ matrix.account-ident }} -u snowddl --env-prefix=${{ matrix.env-prefix }} --apply-unsafe destroy

      - name: "Apply v1"
        run: snowddl -c sample01_01 -a ${{ matrix.account-ident }} -u snowddl --env-prefix=${{ matrix.env-prefix }} --apply-unsafe apply

      - name: "Apply v2"
        run: snowddl -c sample01_02 -a ${{ matrix.account-ident }} -u snowddl --env-prefix=${{ matrix.env-prefix }} --apply-unsafe apply

      - name: "Apply test"
        run: snowddl -c test01 -a ${{ matrix.account-ident }} -u snowddl --env-prefix=${{ matrix.env-prefix }} --apply-unsafe --apply-masking-policy --apply-row-access-policy apply
